import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

def show_self_employed(pd_loan1):
    colors_list = ['lightskyblue', 'gold']
    explode_list = [0.1, 0] # ratio for each continent with which to offset each wedge.
    pd_loan1['Percent'] = pd_loan1['Percent'].astype('float')
    pd_loan1.rename(columns = {'Percent':'Approval on SelfEmployment'}, inplace = True)
    pd_loan1['Approval on SelfEmployment'].plot(kind='pie',
                                figsize=(10, 6),
                                autopct='%1.1f%%', 
                                startangle=90,    
                                shadow=True,       
                                labels=None,         # turn off labels on pie chart
                                pctdistance=1.12,    # the ratio between the center of each pie slice and the start of the text generated by autopct 
                                colors=colors_list,  # add custom colors
                                explode=explode_list # 'explode' lowest 3 continents
                                )
    # scale the title up by 12% to match pctdistance
    plt.title('Loan Approval for Self-employed Applicants', y=1) 
    plt.axis('equal') 
    # add legend
    plt.legend(labels=pd_loan1["self_employed"], loc='upper left') 
    plt.show()

def show_male_applicants(pd_loan2):
    colors_list = ['lightcoral', 'lightgreen']
    explode_list = [0, 0.1] # ratio for each continent with which to offset each wedge.
    pd_loan2['Percent'] = pd_loan2['Percent'].astype('float')
    pd_loan2.rename(columns = {'Percent':'Approval_rate'}, inplace = True)
    pd_loan2['Approval_rate'].plot(kind='pie',
                                figsize=(10, 5),
                                autopct='%1.1f%%', 
                                startangle=90,    
                                shadow=True,       
                                labels=None,         # turn off labels on pie chart
                                pctdistance=1.12,    # the ratio between the center of each pie slice and the start of the text generated by autopct 
                                colors=colors_list,  # add custom colors
                                explode=explode_list # 'explode' lowest 3 continents
                                )
    # scale the title up by 12% to match pctdistance
    plt.title('Married Male Applicants rejected/approved', y=1.05)
    plt.axis('equal') 
    # add legend
    plt.legend(labels=pd_loan2["application_status"], loc='upper left') 
    plt.show()  
def show_top3_months(pd_loan3):   
    #pd_loan3.plot(kind='bar',x='Month', y='Transaction_value',marker='o',color='red',figsize=(10,6))
    pd_loan3.plot(kind='bar',x='Month', y='Transaction_value',color='red',figsize=(10,6))
    plt.title('Top 3 Months Transactions')
    plt.ylabel('Total Transaction')
    plt.xlabel('Month')
    plt.show()
def show_top_hc_transation(pd_loan4):  
    pd_loan4['Transaction_value'] = pd_loan4['Total_Transaction_Value'].astype('float')
    plt.figure(figsize=[8,5])
    sns.barplot(x='branch_code', y='Total_Transaction_Value', data=pd_loan4)
    plt.title('Top Healthcare Transactions by Branch code')
    plt.ylabel('Total Transaction')
    plt.xlabel('Branch Code')
    plt.show()



    